#! /bin/bash

CONTAINER_NAME=$1

cd /etc/digitransit
docker-compose pull
send-to-matrix "🗃️ Restarting digitransit container '$1' on {{ inventory_hostname }}"
docker-compose up -d --no-deps $CONTAINER_NAME
