---
collections:
- ansible.posix
- name: community.general
  version: 10.0.1
- name: community.docker
  version: 3.7.0
- name: devsec.hardening
  version: 10.1.0

# directory containing the collection
#- source: ../../ansible-baseline
#  type: dir
- name: leonardehrenfried.baseline
  version: 1.8.0

roles:
- src: geerlingguy.docker
  version: 4.1.0
- src: geerlingguy.certbot
  version: 4.2.0
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0