---
- apt_repository:
    repo: "deb http://deb.debian.org/debian bookworm-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install packages
  apt:
    state: latest
    default_release: bookworm-backports
    name:
      - pyosmium
      - osm2pgsql
      - osmium-tool
      - curl

- name: Create data directory
  file:
    path: /var/poi/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - poi.yml
  notify: Restart poi service
