---
- apt_repository:
    repo: "deb http://deb.debian.org/debian bookworm-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install packages
  apt:
    state: latest
    default_release: bookworm-backports
    name:
      - pyosmium
      - osm2pgsql
      - osmium-tool
      - curl
      - git
      - luarocks

- name: Install lua-csv package using LuaRocks
  ansible.builtin.command:
    cmd: luarocks install lua-csv
    creates: "/usr/local/share/lua/5.1/lua-csv/"
  become: yes

- name: Create data directory
  file:
    path: /var/poi/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - poi.yml
  notify: Restart poi service

- name: Make script executable
  file:
    dest: /var/poi/import-pois
    mode: "a+x"

- name: Install systemd files
  ansible.builtin.template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - import-pois.service
  notify: Restart import-pois

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - import-pois
    - stadtnavi.lua
  notify: Restart import-pois

- name: Clone osm2pgsql-themepark
  git:
    repo: "https://github.com/osm2pgsql-dev/osm2pgsql-themepark.git"
    dest: "/var/poi/osm2pgsql-themepark"
    version: "60ebeb886f6aaf11c55ea7d393320d153d2b573f"
    force: yes
  notify: Restart import-pois

- name: Copy entire templates folder to server
  copy:
    src: themes
    dest: /var/poi/
    owner: root
    group: root
    mode: '0755'
  notify: Restart import-pois
