---
- apt_repository:
    repo: "deb http://deb.debian.org/debian bookworm-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install packages
  apt:
    state: latest
    default_release: bookworm-backports
    name:
      - pyosmium
      - osm2pgsql
      - osmium-tool
      - curl

- name: Create data directory
  file:
    path: /var/poi/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - poi.yml
  notify: Restart poi service

- name: Make script executable
  file:
    dest: /var/poi/import-pois
    mode: "a+x"

- name: Install systemd files
  ansible.builtin.template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - import-pois.service
  notify: Restart import-pois

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - import-pois
  notify: Restart import-pois

