#! /bin/bash -e

d=`date --iso-8601=date`
file=~/matomo-db-${d}.sql.bz2
export MYSQL_PWD={{ matomo_db_password }}

echo "Dumping mysql file to ${file}"

mysqldump -u matomo --protocol=TCP --port 3306 --databases matomo | bzip2 > $file

echo "Sending file to off-site storage"
curl --silent --show-error --fail -T ${file} -u 'stadtnavi-backup:{{ stadtnavi_backup_password }}' "https://nx9239.your-storageshare.de/remote.php/dav/files/stadtnavi-backup/stadtnavi/{{ server_name }}/"

rm $file