#! /bin/bash

OUTPUT_FILE=nvbw_osm_matches.csv

curl -o - https://data.mfdz.de/mfdz/nvbw_osm_matches.csv.gz | gunzip > ${OUTPUT_FILE}
./nominatim_add_ifopt.py --username nominatim -h localhost -u nominatim --port 5432 --password {{ nominatim_db_password }} ${OUTPUT_FILE}
