alias ll='ls -lah --color'
alias digitransit-logs='sudo journalctl -u digitransit-docker-compose -f'
alias data-builder-logs='sudo journalctl -u data-builder -f'
alias start-data-builder='sudo nohup systemctl start data-builder &'
alias digitransit-docker-compose='docker-compose -f /etc/digitransit/docker-compose.yml'
