alias ll='ls -lah --color'
alias digitransit-logs='sudo journalctl -u digitransit-docker-compose -f'
alias start-graph-build='sudo systemctl start graph-build.service'
alias digitransit-docker-compose='docker-compose -f /etc/digitransit/docker-compose.yml'
alias restart-digitransit='sudo systemctl restart digitransit-docker-compose.service'
