#!/bin/bash

# Adjust homserver, room, and accesstoken to your particular setup
# Script is expecting data to be piped in on STDIN
# Example:
# echo "some text" | send-to-matrix

msgtype=m.text
homeserver=matrix.org
room=!UXrSFkkJoppiEZEfgC:matrix.org
accesstoken={{ matrix_bot_token }}

curl -s -o /dev/null -XPOST -d "$( jq -Rsc --arg msgtype "$msgtype" '{$msgtype, body:.}')" "https://$homeserver/_matrix/client/r0/rooms/$room/send/m.room.message?access_token=$accesstoken"
