---
- name: Install base packages
  package:
    name:
      - nginx
      - npm
      - nodejs
      - node-axios
    state: present

- name: Globally install csv-parser npm package
  npm:
    name: csv-parser
    global: true
  
- name: Copy parse-layers-sheet.js script
  ansible.builtin.template:
    src: templates/parse-layers-sheet.js
    dest: /usr/local/bin/parse-layers-sheet.js
    owner: root
    group: root
    mode: 0755

- name: Create /var/layer-categories directory
  file:
    path: /var/layer-categories
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Caddyfile
  ansible.builtin.template:
    src: templates/services.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy

- name: Create tile cache directory
  file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy nginx site conf
  template:
    src: nginx-site.conf
    dest: /etc/nginx/sites-enabled/services.conf
  notify: Restart nginx